# -*- coding: utf-8 -*-
"""HWork.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10utHYTH6l8Nb_kz9cuhTZTbspLwHaE_e
"""

a = 7
b = "hello"
c = 3.14
print (a,b,c)
print(id(a),id(b),id(c))
print (type(a),type(b),type(c))

a = b
b = "hello"
c = 3.14
print (a,b,c)
print(id(a),id(b),id(c))
print (type(a),type(b),type(c))

a = b = c = 6666
print (a,b,c)
print(id(a),id(b),id(c))
print (type(a),type(b),type(c))

a = input("введите а")
b = input("введите b")
c = input("введите c")
print (a,b,c)
print (type(a),type(b),type(c))
print(id(a),id(b),id(c))